
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBsEUwg","is_bot":false,"login":"SalvadorGracia","name":""},"headRefName":"Salvador-RecRequest-CopyBackend","number":65,"title":"Copied Backend File for Recommendation Requests","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/65"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-CopyBackend","number":64,"title":"Copied over backend code from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/64"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-Migrate","number":63,"title":"Copy files for Backend CRUD API Articles from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/63"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-UCSBOrganization-UCSBOrganizationFixtures","number":62,"title":"Yicong ucsb organization ucsb organization fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/62"}]
