
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-3
pull_requests: [{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"bw-MenuItemReview-Fixtures","number":71,"title":"Created fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/71"},{"author":{"id":"MDQ6VXNlcjg4MjMzMDc2","is_bot":false,"login":"HououinKyouma-2036","name":"HououinKyouma-2036"},"headRefName":"Leo-HelpRequest-Fixtures","number":70,"title":"Create fixtures for HelpRequest","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/70"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-UCSBDiningCommonsMenuItem-Fixtures","number":69,"title":"Created ucsbDiningCommonsMenuItem Fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/69"},{"author":{"id":"U_kgDOBnFNuQ","is_bot":false,"login":"bella-ward","name":"Bella "},"headRefName":"bw-MenuItemReview-backend","number":68,"title":"Copied files for Backend CRUD API MenuItemReview from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/68"},{"author":{"id":"MDQ6VXNlcjg4MjMzMDc2","is_bot":false,"login":"HououinKyouma-2036","name":"HououinKyouma-2036"},"headRefName":"Leo-HelpRequest-CopyBackend","number":67,"title":"Copy files for Backend CRUD API HelpRequest from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/67"},{"author":{"id":"MDQ6VXNlcjcwMzQxMDg0","is_bot":false,"login":"Garrett-Hu","name":""},"headRefName":"Garrett-Articles-Fixtures","number":66,"title":"Create fixtures for Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/66"},{"author":{"id":"U_kgDOBXqLzw","is_bot":false,"login":"erica-ll","name":"Erica Liu"},"headRefName":"Erica-CopyBackend","number":64,"title":"Copied over backend code from team02","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/64"},{"author":{"id":"U_kgDOB7-lTA","is_bot":false,"login":"YicongYan","name":""},"headRefName":"Yicong-UCSBOrganization-UCSBOrganizationFixtures","number":62,"title":"Yicong ucsb organization ucsb organization fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-3/pull/62"}]
